<?php

namespace AppBundle\Repository;

/**
 * DependenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
