<?php

namespace AppBundle\Repository;

/**
 * ParametroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParametroRepository extends \Doctrine\ORM\EntityRepository
{
}
