app_funcionarios:
    resource: "@AppBundle/Resources/config/routing/funcionario.yml"
    prefix:   /funcionarios

homepage:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

productos:
    path:      /productos
    defaults:  { _controller: AppBundle:Default:productos }

productos_by_categoria:
    path:      /{categoriaSlug}/productos
    defaults:  { _controller: AppBundle:Default:productos }

contacto:
    path:      /contacto
    defaults:  { _controller: AppBundle:Default:contacto }

productos2:
    path:      /productos2
    defaults:  { _controller: AppBundle:Default:productos2 }
